---
title: Microservices failures: underestimating platform complexity
title: Microservices on a budget: ignoring platform complexity
date: "2019-05-18"
---

== Microservices failures: underestimating platform complexity
:imagesdir: ./images/2019-05-18-microservices-failures

I think there is a common misconception about microservices out there.

The popular opinion is that microservices supposed to be the cure for all of our problems.  
But I say that by themselves they can cure only half of our problems.  
You are suppose to combine them with the latest DevBizSecQaOps practices to transform your company into the ultimate buzzword producing killing machinegun and achievie Continous Deployment nirvana.

But seriously.

Countless of blogs promised us that microservices will be the the ultimate cure.
They were supposed to enable companies to perform gazzilions deployments per day, scale the system up to infinity while reducing the codebase complexity at the same time.
But few asked what is the price for all of this?

Many forgets that microservices architecture shifts the complexity from code to the platform.

We can describe any software system on how complicated and complex it is.  
System can be made less complicated and complex by removing pieces of it.  
But when splitting a system into pieces we increase its complexity exponentially.

== What is a platform

== Monitoring

== Alarms

== Scalling

== Observability and debugability

> If you are observable I can understand you.

The tools and techniques needed to observe a system composed of couple services vs dozens or hundredths of services are vastly different.
Where one can manage to manually check few services doing so for dozens is not sustainable (I've been there).

The opposite of an observable system is a "black box", where the only thing we can see are the inputs and outputs (or a lack of outpus).
In this very entertaining https://www.youtube.com/watch?v=30jNsCVLpAE[talk] Bryan Cantrill talks about the art of debugability.

> The art of debugging isn't to guess the answer - it is to be able to ask the right questions to know how to answer them. 
> Answered questions are facts, not hyphotesis.

== Platform

First I would like to point out that if you haven't noticed yet this post is my own private opinion on the subject.

There are two cases when starting with microservices architecture:

1. Starting fresh - what we call a greenfield project.
2. Migrating from a monolith by extracting bits from it.

Unfortunally both cases usually suffer from the same symptoms:

> Platform is an afterthought.

== No rewards for paying attention to details

When starting fresh everybody on the project is hyped about microservices.

== Devil is in the details

When starting fresh the core funcionality does not exist yet (obviously) and it will get distributed across many services - that's why we call it a distributed system.

The most common mistakes when starting a distributed system from scratch that I recognize are:

1. 
